/*
 * Generated by gdbus-codegen 2.60.6 from org.freedesktop.UPower.KbdBacklight.xml. DO NOT EDIT.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 */

#ifndef __UP_KBD_BACKLIGHT_GENERATED_H__
#define __UP_KBD_BACKLIGHT_GENERATED_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.freedesktop.UPower.KbdBacklight */

#define UP_TYPE_EXPORTED_KBD_BACKLIGHT (up_exported_kbd_backlight_get_type ())
#define UP_EXPORTED_KBD_BACKLIGHT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), UP_TYPE_EXPORTED_KBD_BACKLIGHT, UpExportedKbdBacklight))
#define UP_IS_EXPORTED_KBD_BACKLIGHT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), UP_TYPE_EXPORTED_KBD_BACKLIGHT))
#define UP_EXPORTED_KBD_BACKLIGHT_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), UP_TYPE_EXPORTED_KBD_BACKLIGHT, UpExportedKbdBacklightIface))

struct _UpExportedKbdBacklight;
typedef struct _UpExportedKbdBacklight UpExportedKbdBacklight;
typedef struct _UpExportedKbdBacklightIface UpExportedKbdBacklightIface;

struct _UpExportedKbdBacklightIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_get_brightness) (
    UpExportedKbdBacklight *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_get_max_brightness) (
    UpExportedKbdBacklight *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_set_brightness) (
    UpExportedKbdBacklight *object,
    GDBusMethodInvocation *invocation,
    gint arg_value);

  void (*brightness_changed) (
    UpExportedKbdBacklight *object,
    gint arg_value);

  void (*brightness_changed_with_source) (
    UpExportedKbdBacklight *object,
    gint arg_value,
    const gchar *arg_source);

};

GType up_exported_kbd_backlight_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *up_exported_kbd_backlight_interface_info (void);
guint up_exported_kbd_backlight_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void up_exported_kbd_backlight_complete_get_max_brightness (
    UpExportedKbdBacklight *object,
    GDBusMethodInvocation *invocation,
    gint value);

void up_exported_kbd_backlight_complete_get_brightness (
    UpExportedKbdBacklight *object,
    GDBusMethodInvocation *invocation,
    gint value);

void up_exported_kbd_backlight_complete_set_brightness (
    UpExportedKbdBacklight *object,
    GDBusMethodInvocation *invocation);



/* D-Bus signal emissions functions: */
void up_exported_kbd_backlight_emit_brightness_changed (
    UpExportedKbdBacklight *object,
    gint arg_value);

void up_exported_kbd_backlight_emit_brightness_changed_with_source (
    UpExportedKbdBacklight *object,
    gint arg_value,
    const gchar *arg_source);



/* D-Bus method calls: */
void up_exported_kbd_backlight_call_get_max_brightness (
    UpExportedKbdBacklight *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean up_exported_kbd_backlight_call_get_max_brightness_finish (
    UpExportedKbdBacklight *proxy,
    gint *out_value,
    GAsyncResult *res,
    GError **error);

gboolean up_exported_kbd_backlight_call_get_max_brightness_sync (
    UpExportedKbdBacklight *proxy,
    gint *out_value,
    GCancellable *cancellable,
    GError **error);

void up_exported_kbd_backlight_call_get_brightness (
    UpExportedKbdBacklight *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean up_exported_kbd_backlight_call_get_brightness_finish (
    UpExportedKbdBacklight *proxy,
    gint *out_value,
    GAsyncResult *res,
    GError **error);

gboolean up_exported_kbd_backlight_call_get_brightness_sync (
    UpExportedKbdBacklight *proxy,
    gint *out_value,
    GCancellable *cancellable,
    GError **error);

void up_exported_kbd_backlight_call_set_brightness (
    UpExportedKbdBacklight *proxy,
    gint arg_value,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean up_exported_kbd_backlight_call_set_brightness_finish (
    UpExportedKbdBacklight *proxy,
    GAsyncResult *res,
    GError **error);

gboolean up_exported_kbd_backlight_call_set_brightness_sync (
    UpExportedKbdBacklight *proxy,
    gint arg_value,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define UP_TYPE_EXPORTED_KBD_BACKLIGHT_PROXY (up_exported_kbd_backlight_proxy_get_type ())
#define UP_EXPORTED_KBD_BACKLIGHT_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), UP_TYPE_EXPORTED_KBD_BACKLIGHT_PROXY, UpExportedKbdBacklightProxy))
#define UP_EXPORTED_KBD_BACKLIGHT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), UP_TYPE_EXPORTED_KBD_BACKLIGHT_PROXY, UpExportedKbdBacklightProxyClass))
#define UP_EXPORTED_KBD_BACKLIGHT_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), UP_TYPE_EXPORTED_KBD_BACKLIGHT_PROXY, UpExportedKbdBacklightProxyClass))
#define UP_IS_EXPORTED_KBD_BACKLIGHT_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), UP_TYPE_EXPORTED_KBD_BACKLIGHT_PROXY))
#define UP_IS_EXPORTED_KBD_BACKLIGHT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), UP_TYPE_EXPORTED_KBD_BACKLIGHT_PROXY))

typedef struct _UpExportedKbdBacklightProxy UpExportedKbdBacklightProxy;
typedef struct _UpExportedKbdBacklightProxyClass UpExportedKbdBacklightProxyClass;
typedef struct _UpExportedKbdBacklightProxyPrivate UpExportedKbdBacklightProxyPrivate;

struct _UpExportedKbdBacklightProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  UpExportedKbdBacklightProxyPrivate *priv;
};

struct _UpExportedKbdBacklightProxyClass
{
  GDBusProxyClass parent_class;
};

GType up_exported_kbd_backlight_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (UpExportedKbdBacklightProxy, g_object_unref)
#endif

void up_exported_kbd_backlight_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
UpExportedKbdBacklight *up_exported_kbd_backlight_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
UpExportedKbdBacklight *up_exported_kbd_backlight_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void up_exported_kbd_backlight_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
UpExportedKbdBacklight *up_exported_kbd_backlight_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
UpExportedKbdBacklight *up_exported_kbd_backlight_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define UP_TYPE_EXPORTED_KBD_BACKLIGHT_SKELETON (up_exported_kbd_backlight_skeleton_get_type ())
#define UP_EXPORTED_KBD_BACKLIGHT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), UP_TYPE_EXPORTED_KBD_BACKLIGHT_SKELETON, UpExportedKbdBacklightSkeleton))
#define UP_EXPORTED_KBD_BACKLIGHT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), UP_TYPE_EXPORTED_KBD_BACKLIGHT_SKELETON, UpExportedKbdBacklightSkeletonClass))
#define UP_EXPORTED_KBD_BACKLIGHT_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), UP_TYPE_EXPORTED_KBD_BACKLIGHT_SKELETON, UpExportedKbdBacklightSkeletonClass))
#define UP_IS_EXPORTED_KBD_BACKLIGHT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), UP_TYPE_EXPORTED_KBD_BACKLIGHT_SKELETON))
#define UP_IS_EXPORTED_KBD_BACKLIGHT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), UP_TYPE_EXPORTED_KBD_BACKLIGHT_SKELETON))

typedef struct _UpExportedKbdBacklightSkeleton UpExportedKbdBacklightSkeleton;
typedef struct _UpExportedKbdBacklightSkeletonClass UpExportedKbdBacklightSkeletonClass;
typedef struct _UpExportedKbdBacklightSkeletonPrivate UpExportedKbdBacklightSkeletonPrivate;

struct _UpExportedKbdBacklightSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  UpExportedKbdBacklightSkeletonPrivate *priv;
};

struct _UpExportedKbdBacklightSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType up_exported_kbd_backlight_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (UpExportedKbdBacklightSkeleton, g_object_unref)
#endif

UpExportedKbdBacklight *up_exported_kbd_backlight_skeleton_new (void);


G_END_DECLS

#endif /* __UP_KBD_BACKLIGHT_GENERATED_H__ */
